apiVersion: v1
kind: ServiceAccount
metadata:
    name: deployment-manager
    namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: deployment-manager
    namespace: default
rules:
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: manage-deployments
    namespace: default
subjects:
    - kind: ServiceAccount
      name: deployment-manager
      namespace: default
roleRef:
    kind: Role
    name: deployment-manager
    apiGroup: rbac.authorization.k8s.io